import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import type { AstroIntegration } from 'astro';
import type { SitemapItem } from '@astrojs/sitemap';
import { getHreflangAlternates } from './seo';

interface PostMetadata {
	slug: string;
	pubDate: Date;
	updatedDate?: Date;
	lastmod: string;
	links: Array<{ lang: string; url: string }>;
}

let cachedMetadata: {
	posts: Map<string, PostMetadata>;
	latestDate: string;
} | null = null;

export function getBlogMetadata() {
	if (cachedMetadata) {
		return cachedMetadata;
	}

	const blogDir = path.resolve('src/content/blog');
	const files = fs
		.readdirSync(blogDir)
		.filter((file) => file.endsWith('.md') || file.endsWith('.mdx'));

	const rawPosts = files.map((file) => {
		const content = fs.readFileSync(path.join(blogDir, file), 'utf-8');
		const slug = file.replace(/\.(md|mdx)$/, '');
		const matchPub = content.match(/pubDate:\s*['"]?([^'"\n\r]+)['"]?/);
		const matchUpd = content.match(/updatedDate:\s*['"]?([^'"\n\r]+)['"]?/);

		const pubDate = matchPub ? new Date(matchPub[1].trim()) : new Date();
		const updatedDate = matchUpd ? new Date(matchUpd[1].trim()) : undefined;
		const lastmod = (updatedDate || pubDate).toISOString();

		return {
			slug,
			pubDate,
			updatedDate,
			lastmod,
		};
	});

	const allSlugs = rawPosts.map((p) => p.slug);
	const origin = 'https://kcrz.dev';

	let maxTimestamp = 0;
	const postsMap = new Map<string, PostMetadata>();

	for (const post of rawPosts) {
		const timestamp = (post.updatedDate || post.pubDate).getTime();
		if (timestamp > maxTimestamp) {
			maxTimestamp = timestamp;
		}

		const alternates = getHreflangAlternates(post.slug, allSlugs, origin);
		const links = alternates.map((alt) => ({
			lang: alt.hreflang,
			url: alt.href,
		}));

		postsMap.set(post.slug, {
			...post,
			links,
		});
	}

	cachedMetadata = {
		posts: postsMap,
		latestDate: new Date(maxTimestamp || Date.now()).toISOString(),
	};

	return cachedMetadata;
}

/**
 * Serializer for @astrojs/sitemap.
 * Enriches URLs with priority, changefreq, lastmod, and multilingual hreflang links.
 */
export function serializeSitemapItem(item: SitemapItem): SitemapItem {
	const { posts, latestDate } = getBlogMetadata();
	const normalizedUrl = item.url.replace(/\/$/, '');

	// 1. Homepage
	if (normalizedUrl === 'https://kcrz.dev') {
		return {
			...item,
			priority: 1.0,
			changefreq: 'weekly',
			lastmod: latestDate,
		};
	}

	// 2. Blog index
	if (normalizedUrl === 'https://kcrz.dev/blog') {
		return {
			...item,
			priority: 0.9,
			changefreq: 'daily',
			lastmod: latestDate,
		};
	}

	// 3. Blog post details
	const postMatch = normalizedUrl.match(/^https:\/\/kcrz\.dev\/blog\/([^/]+)$/);
	if (postMatch) {
		const slug = postMatch[1];
		const post = posts.get(slug);
		if (post) {
			return {
				...item,
				priority: 0.8,
				changefreq: 'monthly',
				lastmod: post.lastmod,
				links: post.links,
			};
		}
	}

	return item;
}

/**
 * Astro integration that creates `sitemap.xml` directly in dist
 * (aliasing the primary sitemap generated by @astrojs/sitemap)
 * so search engines and users can access /sitemap.xml without 404.
 */
export function sitemapXmlIntegration(): AstroIntegration {
	return {
		name: 'kcrz-sitemap-xml',
		hooks: {
			'astro:build:done': async ({ dir, logger }) => {
				const destDir = fileURLToPath(dir);
				const sitemap0Path = path.join(destDir, 'sitemap-0.xml');
				const sitemapXmlPath = path.join(destDir, 'sitemap.xml');

				if (fs.existsSync(sitemap0Path)) {
					fs.copyFileSync(sitemap0Path, sitemapXmlPath);
					logger.info('`sitemap.xml` successfully generated at `dist`');
				} else {
					logger.warn('Could not find `sitemap-0.xml` to generate `sitemap.xml`');
				}
			},
		},
	};
}
